name: Ban list fetch

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  fetch-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download file
        run: |
          curl -o src/plugins/GlobalBans/rb.ts https://cdn.discordapp.com/attachments/1039615673527177296/1047537588388507728/list.ts
          git config --global user.email "roman@realmbot.dev"
          git config --global user.name "Realm Bot"
          git add src/plugins/GlobalBans/rb.ts
          git commit -m "Update Ban Database"
          git push
