name: Ban list fetch

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  fetch-database:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: |
          ls
          curl -o rb.ts https://cdn.discordapp.com/attachments/1039615673527177296/1047537588388507728/list.ts
          git config --global user.email "roman@realmbot.dev"
          git config --global user.name "Realm Bot"
          git add src/plugins/GlobalBans/rb.ts
          git commit -m "Update Ban Database"
          git push
